services:
  mcp-gateway:
    image: docker/mcp-gateway:latest
    command:
      - --transport=sse
      - --servers=github-official
      - --tools=get_commit,get_pull_request,get_pull_request_diff,get_pull_request_files,get_file_contents,add_issue_comment,get_issue_comments,update_pull_request
    use_api_socket: true
    ports:
      - 8811:8811
    secrets:
      - mcp_secret

  app:
    build:
      context: .
      target: dev
    command: ["npm", "run", "dev-server"]
    ports:
      - 4111:4111
    environment:
      MCP_GATEWAY_URL: http://mcp-gateway:8811/sse
    depends_on:
      - mcp-gateway
    models:
      qwen3:
        endpoint_var: OPENAI_BASE_URL_ANALYZER
        model_var: OPENAI_MODEL_ANALYZER
      gemma3:
        endpoint_var: OPENAI_BASE_URL_COMMENT
        model_var: OPENAI_MODEL_COMMENT
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/local/app/src
        - path: ./package-lock.json
          action: rebuild

models:
  gemma3:
    model: ai/gemma3
  qwen3:
    model: ai/qwen3:8B-Q4_0
    context_size: 131000

secrets:
  mcp_secret:
    file: .env
    